### ISSUE TITLE
Can't get URL into Mooscan

### ISSUE THREAD

**Issue by SouthwickSolutions** [vortexau/mooscan#2]
Hello.
When I run
`docker-compose up`
i get the following error:
`mooscan_1  | No URL to scan provided. Nothing to do`

How can I pass a URL as an argument or hard code the URL I am working with?
I tried passing an argument in CLI and hard coding my moodle IP in different areas of the program to no avail.

**Comment by vortexau** [comment]
Hi,
MooScan is not in a working state at the moment as I moved onto a different project during development. Sorry about that.

I would like to get back to it someday, but I haven't had the time or need as yet.

Thanks
